Possibility to specify type attribute
kriasoft/isomorphic-style-loader pull request #163
Opened 2019-06-25 08:40 UTC by BilyachenkoOY

Now it will be possible to specify or type attribute of <style>.
This will allow to fix warning from [W3C validator](https://validator.w3.org/#validate_by_input) "The type attribute for the style element is not needed and should be omitted.".

2019-06-26 14:55 UTC, frenzzy commented
Why not just remove this line at all?
https://github.com/kriasoft/isomorphic-style-loader/blob/a990d947e79b47251f1af827adc81918494413fd/src/insertCss.js#L69

2019-06-26 15:09 UTC, BilyachenkoOY commented
For backward conpatibility at least

2019-08-09 09:56 UTC, BilyachenkoOY commented
@frenzzy Any news on this PR?

2019-08-09 10:32 UTC, frenzzy commented
@BilyachenkoOY sorry, I am not interested in maintenance `isomorphic-style-loader` anymore since I switched to using [Emotion](https://emotion.sh/).

2019-08-09 10:43 UTC, BilyachenkoOY commented
@koistya can you help with this? :)

2021-08-09 21:01 UTC, dazlious requested changes
Just a minor change regarding the code format. Please add at least one test for this in order to allow future maintenance

2026-06-05 11:51 UTC, dazlious approved these changes
Adjusted a bit to simply remove the type attribute, as I hope there is no one out there using HTML4 any longer 🤡

2026-06-05 11:51 UTC, merged